package io.github.cvs0.bytecode.member;

import java.lang.ref.WeakReference;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Represents a mapping from a bytecode program counter (PC) range to a source line number.
 * Optionally includes source file, column number, synthetic flag, original source line, parent reference, and metadata for richer debugging, obfuscation, and source mapping.
 * <p>
 * The range is defined as [startPc, endPc), where endPc is exclusive. If endPc is negative, the range is open-ended.
 * </p>
 */
public class LineNumber {
    /**
     * The start program counter (inclusive) for this line number mapping.
     */
    private int startPc;

    /**
     * The end program counter (exclusive) for this line number mapping, or -1 if open-ended.
     */
    private int endPc;

    /**
     * The source line number.
     */
    private int lineNumber;

    /**
     * The source file name, or null if not available.
     */
    private String sourceFile;

    /**
     * The source column number, or -1 if not available.
     */
    private int columnNumber;

    /**
     * True if this line is synthetic or generated by the compiler.
     */
    private boolean synthetic;

    /**
     * Optional original source line (for reversible mapping/obfuscation).
     */
    private String originalSourceLine;

    /**
     * Optional metadata for extensibility (e.g., obfuscation hints, tags).
     */
    private Map<String, Object> metadata;

    /**
     * Optional weak reference to the parent (e.g., method or class).
     * Not serialized.
     */
    private transient WeakReference<Object> parent;

    /**
     * Constructs a LineNumber with only startPc and lineNumber. Range is open-ended, no file/column info.
     * Synthetic is false, no metadata or parent.
     * @param startPc the start program counter
     * @param lineNumber the source line number
     */
    public LineNumber(int startPc, int lineNumber) {
        this(startPc, -1, lineNumber, null, -1, false, null, null, null);
    }

    /**
     * Constructs a LineNumber with a start and end PC, and a line number. No file/column info.
     * Synthetic is false, no metadata or parent.
     * @param startPc the start program counter
     * @param endPc the end program counter (exclusive), or -1 if open-ended
     * @param lineNumber the source line number
     */
    public LineNumber(int startPc, int endPc, int lineNumber) {
        this(startPc, endPc, lineNumber, null, -1, false, null, null, null);
    }

    /**
     * Constructs a LineNumber with all fields except metadata and parent.
     * @param startPc the start program counter
     * @param endPc the end program counter (exclusive), or -1 if open-ended
     * @param lineNumber the source line number
     * @param sourceFile the source file name, or null
     * @param columnNumber the source column number, or -1
     */
    public LineNumber(int startPc, int endPc, int lineNumber, String sourceFile, int columnNumber) {
        this(startPc, endPc, lineNumber, sourceFile, columnNumber, false, null, null, null);
    }

    /**
     * Constructs a LineNumber with all fields except parent.
     * @param startPc the start program counter
     * @param endPc the end program counter (exclusive), or -1 if open-ended
     * @param lineNumber the source line number
     * @param sourceFile the source file name, or null
     * @param columnNumber the source column number, or -1
     * @param synthetic true if this line is synthetic
     * @param originalSourceLine the original source line, or null
     * @param metadata metadata map, or null for empty
     */
    public LineNumber(int startPc, int endPc, int lineNumber, String sourceFile, int columnNumber, boolean synthetic, String originalSourceLine, Map<String, Object> metadata) {
        this(startPc, endPc, lineNumber, sourceFile, columnNumber, synthetic, originalSourceLine, metadata, null);
    }

    /**
     * Constructs a LineNumber with all fields.
     * @param startPc the start program counter
     * @param endPc the end program counter (exclusive), or -1 if open-ended
     * @param lineNumber the source line number
     * @param sourceFile the source file name, or null
     * @param columnNumber the source column number, or -1
     * @param synthetic true if this line is synthetic
     * @param originalSourceLine the original source line, or null
     * @param metadata metadata map, or null for empty
     * @param parent parent reference, or null
     */
    public LineNumber(int startPc, int endPc, int lineNumber, String sourceFile, int columnNumber, boolean synthetic, String originalSourceLine, Map<String, Object> metadata, Object parent) {
        this.startPc = startPc;
        this.endPc = endPc;
        this.lineNumber = lineNumber;
        this.sourceFile = sourceFile;
        this.columnNumber = columnNumber;
        this.synthetic = synthetic;
        this.originalSourceLine = originalSourceLine;
        this.metadata = (metadata != null) ? new HashMap<>(metadata) : new HashMap<>();
        this.parent = (parent != null) ? new WeakReference<>(parent) : null;
    }

    /**
     * Gets the start program counter (inclusive).
     * @return the start PC
     */
    public int getStartPc() {
        return startPc;
    }

    /**
     * Sets the start program counter (inclusive).
     * @param startPc the start PC
     */
    public void setStartPc(int startPc) {
        this.startPc = startPc;
    }

    /**
     * Gets the end program counter (exclusive), or -1 if open-ended.
     * @return the end PC
     */
    public int getEndPc() {
        return endPc;
    }

    /**
     * Sets the end program counter (exclusive), or -1 if open-ended.
     * @param endPc the end PC
     */
    public void setEndPc(int endPc) {
        this.endPc = endPc;
    }

    /**
     * Gets the source line number.
     * @return the line number
     */
    public int getLineNumber() {
        return lineNumber;
    }

    /**
     * Sets the source line number.
     * @param lineNumber the line number
     */
    public void setLineNumber(int lineNumber) {
        this.lineNumber = lineNumber;
    }

    /**
     * Gets the source file name, or null if not available.
     * @return the source file name
     */
    public String getSourceFile() {
        return sourceFile;
    }

    /**
     * Sets the source file name.
     * @param sourceFile the source file name
     */
    public void setSourceFile(String sourceFile) {
        this.sourceFile = sourceFile;
    }

    /**
     * Gets the source column number, or -1 if not available.
     * @return the column number
     */
    public int getColumnNumber() {
        return columnNumber;
    }

    /**
     * Sets the source column number, or -1 if not available.
     * @param columnNumber the column number
     */
    public void setColumnNumber(int columnNumber) {
        this.columnNumber = columnNumber;
    }

    /**
     * Returns true if the given program counter is within this line's range.
     * If endPc >= 0, checks startPc <= pc < endPc. Otherwise, checks pc >= startPc.
     * @param pc the program counter
     * @return true if the pc is covered by this line number entry
     */
    public boolean covers(int pc) {
        if (endPc >= 0) {
            return pc >= startPc && pc < endPc;
        } else {
            return pc >= startPc;
        }
    }

    /**
     * Returns true if this line is synthetic or compiler-generated.
     */
    public boolean isSynthetic() {
        return synthetic;
    }

    /**
     * Sets whether this line is synthetic or compiler-generated.
     */
    public void setSynthetic(boolean synthetic) {
        this.synthetic = synthetic;
    }

    /**
     * Gets the original source line (for reversible mapping/obfuscation).
     */
    public String getOriginalSourceLine() {
        return originalSourceLine;
    }

    /**
     * Sets the original source line (for reversible mapping/obfuscation).
     */
    public void setOriginalSourceLine(String originalSourceLine) {
        this.originalSourceLine = originalSourceLine;
    }

    /**
     * Gets the metadata map (never null).
     */
    public Map<String, Object> getMetadata() {
        return metadata;
    }

    /**
     * Sets the metadata map (replaces all entries).
     */
    public void setMetadata(Map<String, Object> metadata) {
        this.metadata = (metadata != null) ? new HashMap<>(metadata) : new HashMap<>();
    }

    /**
     * Gets the parent reference, or null if not set or GC'd.
     */
    public Object getParent() {
        return (parent != null) ? parent.get() : null;
    }

    /**
     * Sets the parent reference (weak reference).
     */
    public void setParent(Object parent) {
        this.parent = (parent != null) ? new WeakReference<>(parent) : null;
    }

    /**
     * Returns a string representation of this line number entry.
     */
    @Override
    public String toString() {
        return "LineNumber{" +
                "startPc=" + startPc +
                ", endPc=" + endPc +
                ", lineNumber=" + lineNumber +
                (sourceFile != null ? ", sourceFile='" + sourceFile + '\'' : "") +
                (columnNumber >= 0 ? ", columnNumber=" + columnNumber : "") +
                (synthetic ? ", synthetic=true" : "") +
                (originalSourceLine != null ? ", originalSourceLine='" + originalSourceLine + '\'' : "") +
                (!metadata.isEmpty() ? ", metadata=" + metadata : "") +
                (getParent() != null ? ", parent=" + getParent() : "") +
                '}';
    }

    /**
     * Checks equality with another object.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        LineNumber that = (LineNumber) o;
        return startPc == that.startPc &&
                endPc == that.endPc &&
                lineNumber == that.lineNumber &&
                columnNumber == that.columnNumber &&
                synthetic == that.synthetic &&
                Objects.equals(sourceFile, that.sourceFile) &&
                Objects.equals(originalSourceLine, that.originalSourceLine) &&
                Objects.equals(metadata, that.metadata);
        // parent is intentionally not compared (transient, context only)
    }

    /**
     * Returns a hash code for this line number entry.
     */
    @Override
    public int hashCode() {
        return Objects.hash(startPc, endPc, lineNumber, sourceFile, columnNumber, synthetic, originalSourceLine, metadata);
    }
}